name: Build and Deploy to AWS ECS

on:
  push:
    branches:
      - 'master'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

jobs:
  build-and-deploy:
    name: Build, Push to ECR, Deploy to ECS
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build:prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Render Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
  cleanup:
    runs-on: ubuntu-latest
    name: Clean up unused task definitions
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      
      - name: Cleanup Old Task Definitions
        run: |
          FAMILY="users_ui_task"
          KEEP=5

          TASKS=$(aws ecs list-task-definitions \
            --family-prefix $FAMILY \
            --sort ASC \
            --query 'taskDefinitionArns[*]' \
            --output text)

          TOTAL=$(echo "$TASKS" | tr '\t' '\n' | wc -l)

          echo "TOTAL TASK DEFINITIONS: $TOTAL"

          DELETE_COUNT=$((TOTAL - KEEP))

          echo "DELETE COUNT: $DELETE_COUNT"

          if [ "$DELETE_COUNT" -le 0 ]; then
            echo "Nothing to delete"
            exit 0
          fi

          COUNT=0
          for TASK in $TASKS; do
            COUNT=$((COUNT+1))
            if [ "$COUNT" -le "$DELETE_COUNT" ]; then
              echo "Deregistering $TASK"
              aws ecs deregister-task-definition --task-definition $TASK
            fi
          done